apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-flask-argocd-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mdzahid786/flask-app.git
    targetRevision: HEAD
    path: k8s-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
