apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: flask-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/containervolume/flask-backend/data"
  persistentVolumeReclaimPolicy: Retain
