name: Build and Push with Docker Compose

on:
  push:
    branches:
      - dynamic-build-code   # run only when code is merged into master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 3: Build & Tag images
      - name: Build backend and frontend images
        run: |
          COMMIT_SHA=${GITHUB_SHA::7}   # short commit SHA (7 chars)

          # Backend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-backend:latest ./backend
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-backend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-backend:$COMMIT_SHA

          # Frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-frontend:latest ./frontend
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-frontend:latest ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-frontend:$COMMIT_SHA

      # Step 4: Push images
      - name: Push backend and frontend images
        run: |
          COMMIT_SHA=${GITHUB_SHA::7}

          # Push backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-backend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-backend:$COMMIT_SHA

          # Push frontend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-app-frontend:$COMMIT_SHA
